### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by oakca**
`/berlin_example` creates plot using `osmnx` package via downloading from `openstreetmap` and plotting in `matplotlib` plots.

`/interactive_map_example` creates interactive map using `folium` package as `html` file.

### CODE REVIEW

**Comment by jnnr** [comment]
Thanks for your effort! 
I suggest the following:
* Merge the two examples to one. Create on dummy network and show how you can plot it either by creating a static map or an interactive map using the respective function.
* The example for interactive maps has no edges yet. Make sure that in the interactive map, the edges between the nodes are displayed. 
* Allow coloring of the edges in the interactive map according to some edge attribute (can be used later to show e.g. diameter of the pipes, pressure loss, ...)

**Comment by jnnr** [comment]
For the static map, you might want to try matplotlib's basemap:
https://basemaptutorial.readthedocs.io/en/latest/index.htmla

**Comment by oakca** [comment]
I have done the changes, will close this one and open another PR @jnnr

**Comment by jnnr** [comment]
If you continue working on this branch, you can leave the PR open and push new commits!

**Comment by oakca** [comment]
I wow... I did not know that. So I already close this one and open the second one and close it again, because I wanted to implement some arrows... Sorry for that

**Pull request closed without merging**
